import { enumCompetences } from "../app/fm/models/competence.model";
import { enumSauvegarde } from "../app/fm/models/sauvegarde.model";

export const ClasseData = 
[
	{
		'IdClasse': '0',
		'NomClasse': 'Choisir une classe',
		'Sauvegardes': [
			{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
			{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
			{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
			{'nom': enumSauvegarde.Volonte, 'Valeur': 0},
			],
	},
	{
	'IdClasse': 'Guerrier',
	'NomClasse': 'Guerrier',
	'PointVieBase': 15,
	'PointVieNiveau': 6,
	'Recuperation': 9,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 2},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.ConnDeLaRue, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Magicien',
	'NomClasse': 'Magicien',
	'PointVieBase': 10,
	'PointVieNiveau': 4,
	'Recuperation': 6,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 2},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': true},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Exploration, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Nature, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'MaitreDeGuerre',
	'NomClasse': 'Maître de guerre',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 4,
	'Competences': [
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Paladin',
	'NomClasse': 'Paladin',
	'PointVieBase': 15,
	'PointVieNiveau': 6,
	'Recuperation': 10,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': true},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Pretre',
	'NomClasse': 'Prêtre',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 2},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': true},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Rodeur',
	'NomClasse': 'Rôdeur',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 6,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	'NombreCompetence': 4,
	'Competences': [
		{'nom': enumCompetences.Acrobaties, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Discretion, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Sorcier',
	'NomClasse': 'Sorcier',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 6,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 4,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': false},
		{'nom': enumCompetences.Bluff, 'obligatoire': false},
		{'nom': enumCompetences.ConnDeLaRue, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Larcin, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Voleur',
	'NomClasse': 'Voleur',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 6,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 2},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	'NombreCompetence': 4,
	'Competences': [
		{'nom': enumCompetences.Acrobaties, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Bluff, 'obligatoire': false},
		{'nom': enumCompetences.ConnDeLaRue, 'obligatoire': false},
		{'nom': enumCompetences.Discretion, 'obligatoire': true},
		{'nom': enumCompetences.Exploration, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Larcin, 'obligatoire': true},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Barbare',
	'NomClasse': 'Barbare',
	'PointVieBase': 15,
	'PointVieNiveau': 6,
	'Recuperation': 8,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 2},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Acrobaties, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Nature, 'obligatoire': false},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Barde',
	'NomClasse': 'Barde',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 4,
	'Competences': [
		{'nom': enumCompetences.Acrobaties, 'obligatoire': false},
		{'nom': enumCompetences.Arcanes, 'obligatoire': true},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Bluff, 'obligatoire': false},
		{'nom': enumCompetences.ConnDeLaRue, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Exploration, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Nature, 'obligatoire': false},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Druide',
	'NomClasse': 'Druide',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Nature, 'obligatoire': true},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Ensorceleur',
	'NomClasse': 'Ensorceleur',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 6,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 2},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': true},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Bluff, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Exploration, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Nature, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Gardien',
	'NomClasse': 'Gardien',
	'PointVieBase': 17,
	'PointVieNiveau': 7,
	'Recuperation': 9,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Exploration, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Nature, 'obligatoire': true},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Invocateur',
	'NomClasse': 'Invocateur',
	'PointVieBase': 10,
	'PointVieNiveau': 4,
	'Recuperation': 6,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': true},
		],
	},
	{
	'IdClasse': 'Shaman',
	'NomClasse': 'Shaman',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Nature, 'obligatoire': true},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Vengeur',
	'NomClasse': 'Vengeur',
	'PointVieBase': 14,
	'PointVieNiveau': 6,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Acrobaties, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.ConnDeLaRue, 'obligatoire': false},
		{'nom': enumCompetences.Discretion, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': true},
		],
	},
	{
	'IdClasse': 'Batailleur',
	'NomClasse': 'Batailleur',
	'PointVieBase': 15,
	'PointVieNiveau': 6,
	'Recuperation': 9,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 2},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Bluff, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Flamboyant',
	'NomClasse': 'Flamboyant',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 4,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Bluff, 'obligatoire': false},
		{'nom': enumCompetences.ConnDeLaRue, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Limier',
	'NomClasse': 'Limier',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Acrobaties, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Discretion, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Nature, 'obligatoire': false},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Moine',
	'NomClasse': 'Moine',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	'NombreCompetence': 4,
	'Competences': [
		{'nom': enumCompetences.Acrobaties, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Discretion, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Larcin, 'obligatoire': false},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'PretreDesRunes',
	'NomClasse': 'Prêtre des runes',
	'PointVieBase': 12,
	'PointVieNiveau': 5,
	'Recuperation': 7,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 2},
		],
	'NombreCompetence': 3,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': false},
		{'nom': enumCompetences.Athletisme, 'obligatoire': false},
		{'nom': enumCompetences.Endurance, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Larcin, 'obligatoire': false},
		{'nom': enumCompetences.Religion, 'obligatoire': false},
		{'nom': enumCompetences.Soins, 'obligatoire': false},
		],
	},
	{
	'IdClasse': 'Psion',
	'NomClasse': 'Psion',
	'PointVieBase': 12,
	'PointVieNiveau': 4,
	'Recuperation': 6,
	'Sauvegardes': [
		{'nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'nom': enumSauvegarde.Volonte, 'Valeur': 2},
		],
	'NombreCompetence': 4,
	'Competences': [
		{'nom': enumCompetences.Arcanes, 'obligatoire': false},
		{'nom': enumCompetences.Bluff, 'obligatoire': false},
		{'nom': enumCompetences.Diplomatie, 'obligatoire': false},
		{'nom': enumCompetences.Exploration, 'obligatoire': false},
		{'nom': enumCompetences.Histoire, 'obligatoire': false},
		{'nom': enumCompetences.Intuition, 'obligatoire': false},
		{'nom': enumCompetences.Intimidation, 'obligatoire': false},
		{'nom': enumCompetences.Perception, 'obligatoire': false},
		],
	},
]