import { enumCaracteristique } from "../app/fm/models/caracteristique.model";
import { enumCompetences } from "../app/fm/models/competence.model";
//import { enumTaille, enumVision } from "./race.js";
import { enumSauvegarde } from "../app/fm/models/sauvegarde.model";

export const RaceData = 
[
	/*{
		'IdRace': '0',
		'NomRace': 'Choisir une race'
	},*/
	{
	'IdRace': 'Drakeide',
	'NomRace': 'Drakéide',
	'Vitesse': 6,
	'TailleMini': 185,
	'TailelMaxi': 200,
	'PoidsMini': 110,
	'PoidsMaxi': 160,
	'Taille': 'M',
	'Vision': 'Normale',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 2},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 2},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 2 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 2 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Tieffelin',
	'NomRace': 'Tieffelin',
	'Vitesse': 6,
	'TailleMini': 165,
	'TailelMaxi': 185,
	'PoidsMini': 70,
	'PoidsMaxi': 115,
	'Taille': 'M',
	'Vision': 'Nocturne',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 2},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 2},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 2 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 2 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Elfe',
	'NomRace': 'Elfe',
	'Vitesse': 7,
	'TailleMini': 160,
	'TailelMaxi': 180,
	'PoidsMini': 65,
	'PoidsMaxi': 85,
	'Taille': 'M',
	'Vision': 'Nocturne',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 2},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 2},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 2 },
		{'Nom': enumCompetences.Perception, 'Valeur': 2 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Eladrin',
	'NomRace': 'Eladrin',
	'Vitesse': 6,
	'TailleMini': 165,
	'TailelMaxi': 185,
	'PoidsMini': 65,
	'PoidsMaxi': 90,
	'Taille': 'M',
	'Vision': 'Nocturne',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 2},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 2},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 2 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 2 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	},
	{
	'IdRace': 'Drow',
	'NomRace': 'Drow',
	'Vitesse': 6,
	'TailleMini': 0,
	'TailelMaxi': 0,
	'PoidsMini': 0,
	'PoidsMaxi': 0,
	'Taille': '',
	'Vision': '',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 2},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 2},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Nain',
	'NomRace': 'Nain',
	'Vitesse': 5,
	'TailleMini': 125,
	'TailelMaxi': 145,
	'PoidsMini': 80,
	'PoidsMaxi': 110,
	'Taille': 'M',
	'Vision': 'Nocturne',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 2},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 2},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 2 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 2 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Duergar',
	'NomRace': 'Duergar',
	'Vitesse': 5,
	'TailleMini': 0,
	'TailelMaxi': 0,
	'PoidsMini': 0,
	'PoidsMaxi': 0,
	'Taille': '',
	'Vision': '',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 2},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 2},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Orc',
	'NomRace': 'Orc',
	'Vitesse': 6,
	'TailleMini': 195,
	'TailelMaxi': 230,
	'PoidsMini': 85,
	'PoidsMaxi': 125,
	'Taille': 'M',
	'Vision': 'Nocturne',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 2},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 2},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 2 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 2 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Gnome',
	'NomRace': 'Gnome',
	'Vitesse': 5,
	'TailleMini': 0,
	'TailelMaxi': 0,
	'PoidsMini': 0,
	'PoidsMaxi': 0,
	'Taille': '',
	'Vision': '',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 2},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 2},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 2 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 2 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Gobelin',
	'NomRace': 'Gobelin',
	'Vitesse': 5,
	'TailleMini': 0,
	'TailelMaxi': 0,
	'PoidsMini': 0,
	'PoidsMaxi': 0,
	'Taille': '',
	'Vision': '',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Deva',
	'NomRace': 'Déva',
	'Vitesse': 6,
	'TailleMini': 0,
	'TailelMaxi': 0,
	'PoidsMini': 0,
	'PoidsMaxi': 0,
	'Taille': '',
	'Vision': '',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 2},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 2},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 2 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 2 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Humain',
	'NomRace': 'Humain',
	'Vitesse': 6,
	'TailleMini': 165,
	'TailelMaxi': 185,
	'PoidsMini': 65,
	'PoidsMaxi': 110,
	'Taille': 'M',
	'Vision': 'Normale',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	},
	{
	'IdRace': 'DemiElfe',
	'NomRace': 'Demi-elfe',
	'Vitesse': 6,
	'TailleMini': 165,
	'TailelMaxi': 185,
	'PoidsMini': 65,
	'PoidsMaxi': 85,
	'Taille': 'M',
	'Vision': 'Nocturne',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 2},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 2},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 2 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 2 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Halfelin',
	'NomRace': 'Halfelin',
	'Vitesse': 6,
	'TailleMini': 115,
	'TailelMaxi': 125,
	'PoidsMini': 37,
	'PoidsMaxi': 42,
	'Taille': 'P',
	'Vision': 'Normale',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 2},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 2},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 2 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 2 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Deva',
	'NomRace': 'Deva',
	'Vitesse': 6,
	'TailleMini': 200,
	'TailelMaxi': 215,
	'PoidsMini': 87,
	'PoidsMaxi': 140,
	'Taille': 'M',
	'Vision': 'Normale',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 2},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 2},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 2 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 2 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 1},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 1},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	},
	{
	'IdRace': 'Gnome',
	'NomRace': 'Gnome',
	'Vitesse': 5,
	'TailleMini': 110,
	'TailelMaxi': 120,
	'PoidsMini': 25,
	'PoidsMaxi': 37,
	'Taille': 'P',
	'Vision': 'Nocturne',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 2},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 2},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 2 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 2 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'Goliath',
	'NomRace': 'Goliath',
	'Vitesse': 6,
	'TailleMini': 240,
	'TailelMaxi': 250,
	'PoidsMini': 140,
	'PoidsMaxi': 170,
	'Taille': 'M',
	'Vision': 'Normale',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 2},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 2},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 2 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 2 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 1},
		],
	},
	{
	'IdRace': 'DemiOrc',
	'NomRace': 'Demi-Orc',
	'Vitesse': 6,
	'TailleMini': 190,
	'TailelMaxi': 210,
	'PoidsMini': 77,
	'PoidsMaxi': 112,
	'Taille': 'M',
	'Vision': 'Nocturne',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 2},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 2},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 0},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 2 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 2 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
	'IdRace': 'FeralLongueDent',
	'NomRace': 'Féral Longue-Dent',
	'Vitesse': 6,
	'TailleMini': 180,
	'TailelMaxi': 200,
	'PoidsMini': 65,
	'PoidsMaxi': 90,
	'Taille': 'M',
	'Vision': 'Nocturne',
	'Caracteristiques': [
		{'Nom': enumCaracteristique.AForce, 'Valeur': 2},
		{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
		{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
		{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
		{'Nom': enumCaracteristique.ESagesse, 'Valeur': 2},
		{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
		],
	'Competences': [
		{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
		{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
		{'Nom': enumCompetences.Athletisme, 'Valeur': 2 },
		{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
		{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
		{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
		{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
		{'Nom': enumCompetences.Endurance, 'Valeur': 2 },
		{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
		{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
		{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
		{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
		{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
		{'Nom': enumCompetences.Nature, 'Valeur': 0 },
		{'Nom': enumCompetences.Perception, 'Valeur': 0 },
		{'Nom': enumCompetences.Religion, 'Valeur': 0 },
		{'Nom': enumCompetences.Soins, 'Valeur': 0 },
		],
	'Sauvegardes': [
		{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
		{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
		{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
		{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
		],
	},
	{
		'IdRace': 'FeralGriffeEfillee',
		'NomRace': 'Féral Griffe-Efillée',
		'Vitesse': 6,
		'TailleMini': 180,
		'TailelMaxi': 200,
		'PoidsMini': 65,
		'PoidsMaxi': 90,
		'Taille': 'M',
		'Vision': 'Nocturne',
		'Caracteristiques': [
			{'Nom': enumCaracteristique.AForce, 'Valeur': 0},
			{'Nom': enumCaracteristique.BConstitution, 'Valeur': 0},
			{'Nom': enumCaracteristique.CDexterite, 'Valeur': 2},
			{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
			{'Nom': enumCaracteristique.ESagesse, 'Valeur': 2},
			{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
			],
		'Competences': [
			{'Nom': enumCompetences.Acrobaties, 'Valeur': 2 },
			{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
			{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
			{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
			{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
			{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
			{'Nom': enumCompetences.Discretion, 'Valeur': 2 },
			{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
			{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
			{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
			{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
			{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
			{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
			{'Nom': enumCompetences.Nature, 'Valeur': 0 },
			{'Nom': enumCompetences.Perception, 'Valeur': 0 },
			{'Nom': enumCompetences.Religion, 'Valeur': 0 },
			{'Nom': enumCompetences.Soins, 'Valeur': 0 },
			],
		'Sauvegardes': [
			{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
			{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
			{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
			{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
			],
		},
		{
		'IdRace': 'Minotaure',
		'NomRace': 'Minotaure',
		'Vitesse': 6,
		'TailleMini': 215,
		'TailelMaxi': 230,
		'PoidsMini': 160,
		'PoidsMaxi': 175,
		'Taille': 'M',
		'Vision': 'Normale',
		'Caracteristiques': [
			{'Nom': enumCaracteristique.AForce, 'Valeur': 2},
			{'Nom': enumCaracteristique.BConstitution, 'Valeur': 1},
			{'Nom': enumCaracteristique.CDexterite, 'Valeur': 0},
			{'Nom': enumCaracteristique.DIntelligence, 'Valeur': 0},
			{'Nom': enumCaracteristique.ESagesse, 'Valeur': 1},
			{'Nom': enumCaracteristique.FCharisme, 'Valeur': 0},
			],
		'Competences': [
			{'Nom': enumCompetences.Acrobaties, 'Valeur': 0 },
			{'Nom': enumCompetences.Arcanes, 'Valeur': 0 },
			{'Nom': enumCompetences.Athletisme, 'Valeur': 0 },
			{'Nom': enumCompetences.Bluff, 'Valeur': 0 },
			{'Nom': enumCompetences.ConnDeLaRue, 'Valeur': 0 },
			{'Nom': enumCompetences.Diplomatie, 'Valeur': 0 },
			{'Nom': enumCompetences.Discretion, 'Valeur': 0 },
			{'Nom': enumCompetences.Endurance, 'Valeur': 0 },
			{'Nom': enumCompetences.Exploration, 'Valeur': 0 },
			{'Nom': enumCompetences.Histoire, 'Valeur': 0 },
			{'Nom': enumCompetences.Intuition, 'Valeur': 0 },
			{'Nom': enumCompetences.Intimidation, 'Valeur': 0 },
			{'Nom': enumCompetences.Larcin, 'Valeur': 0 },
			{'Nom': enumCompetences.Nature, 'Valeur': 2 },
			{'Nom': enumCompetences.Perception, 'Valeur': 2 },
			{'Nom': enumCompetences.Religion, 'Valeur': 0 },
			{'Nom': enumCompetences.Soins, 'Valeur': 0 },
			],
		'Sauvegardes': [
			{'Nom': enumSauvegarde.ClasseArmure, 'Valeur': 0},
			{'Nom': enumSauvegarde.Vigueur, 'Valeur': 0},
			{'Nom': enumSauvegarde.Reflexe, 'Valeur': 0},
			{'Nom': enumSauvegarde.Volonte, 'Valeur': 0},
			],
		},
	]	